language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  # downloading the latest version of the linaro toolchain. 
  - wget -c https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/bin/
  - arm-linux-gnueabihf-gcc --version
  
  - sudo apt-get install bc


#######################################################################################


before_script:

  #DST_PROJECT is the beaglescope project directory
  - export DST_PROJECT=$PWD

  # The SOURCE_VERSION and SOURCE_LOCATION together define the complete link to the gzipped tar file of 
  # linux source code and its .config file against which the beaglescope project is build to test it.
  #
  # SOURCE_BRANCH="a.branch"
  # SOURCE_VERSION="x.y.z"
  # SOURCE_REPO="the_repo"
  # SOURCE_LOCATION="https://example-location.com/source"
  # Combined source link will be = "https://example-location.com/source/the_repo/archive/a.branch-x.y.z.tar.gz"
  # and
  # Combined .config link will be = "http://rcn-ee.net/deb/jessie-armhf/v$SOURCE_VERSION/defconfig"
 
  - export SOURCE_BRANCH="4.4.12"
  - export SOURCE_VERSION="ti-r31"
  - export SOURCE_REPO="linux-stable-rcn-ee"
  - export SOURCE_LOCATION="https://github.com/RobertCNelson"
  
  # download and extract the linux source code.
  - wget "$SOURCE_LOCATION/$SOURCE_REPO/archive/$SOURCE_BRANCH-$SOURCE_VERSION.tar.gz"
  - tar -zvxf $SOURCE_BRANCH-$SOURCE_VERSION.tar.gz

  # DST_KERNEL is the path to the linux source code
  - export DST_KERNEL=$PWD/$SOURCE_REPO-$SOURCE_BRANCH-$SOURCE_VERSION


#######################################################################################


script:

  # exporting the variable to be used by make utility  
  - export ARCH=arm 
  - export CROSS_COMPILE=arm-linux-gnueabihf-

  # download the .config file for the chosen linux version and
  # preparing the kernel source
  
  - cd $DST_KERNEL
  - make -j3 mrproper ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION=-$SOURCE_VERSION
  - wget -c "http://rcn-ee.net/deb/jessie-armhf/v$SOURCE_BRANCH-$SOURCE_VERSION/defconfig" -O .config
  - make -j3 modules ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION=-$SOURCE_VERSION 2>&1 

  # building the project
  - cd $DST_PROJECT/
  - make KDIR=$DST_KERNEL ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION=-$SOURCE_VERSION
